[ExecuTorch] Separate `extension.Module` Namespaces from Aten and non-Aten
Pull Request resolved: https://github.com/pytorch/executorch/pull/10576

# Context

Separate `extension.Module` Namespaces to be `executorch::extension::module` and `executorch::extension::module::aten`, otherwise if a package relies on both aten and non-aten of the same implementation and the namespace is the same, there will be duplicate symbol issue like:

```
ld.lld: error: duplicate symbol: vtable for executorch::extension::Module
>>> defined at {redacted}/executorch/extension/module/__module__/__stripped__/module.cpp.pic.stripped.o:(vtable for executorch::extension::Module)
>>> defined at {redacted}/executorch/extension/module/__module_aten__/__stripped__/module.cpp.pic.stripped.o:
```

# Proposal

Doing something similar to what we already did for `bundled_program` in https://github.com/pytorch/executorch/pull/10307

Since `extension.Module` is a public API, we introduce a namespace alias, so that existing use cases won't get affected. Since namespace alias doesn't create additional symbols, there won't be duplicate symbol issue.

ghstack-source-id: 281229770
@exported-using-ghexport

Differential Revision: [D73903870](https://our.internmc.facebook.com/intern/diff/D73903870/)